import { type NextPage } from "next";
import Head from "next/head";

const SingleRestaurantPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex justify-center">
        <div>Restaurant View</div>
      </main>
    </>
  );
};

export default SingleRestaurantPage;
